#!/usr/bin/env python3
"""Write one app icon per theme, for both apps, as SVG masters.

    python3 tools/theme-icons.py        # from the repo root

Classic is not here: it is icon-dark.svg / icon-light.svg / ios/Support/icon-ios.svg,
unchanged. Each theme's icon is the same badge — so it is still recognisably this app
in the Dock and on the home screen — in the theme's colours, on a gradient of its
ground. Nothing else: scenery in the plate was clipped by iOS's corner mask, and at
29–64 px it was noise.

Outputs icons/themes/<id>-mac.svg (squircle plate on a transparent canvas, like
icon-dark.svg) and icons/themes/<id>-ios.svg (full-bleed and opaque: iOS masks the
corners itself). build-mac-app.sh and ios/make-icon.sh rasterise them.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "icons", "themes")

BADGE = ("M172.32,19.36c-2-7.6-8-13.6-15.6-15.6C143.12,0,88,0,88,0S32.88,0,19.28,3.76"
         "c-7.6,2-13.6,8-15.6,15.6C0,32.96,0,62,0,62s0,29.04,3.68,42.64c2,7.6,8,13.6,15.6,"
         "15.6C32.88,124,88,124,88,124s55.12,0,68.72-3.76c7.6-2,13.6-8,15.6-15.6C176,91.04,"
         "176,62,176,62S176,32.96,172.32,19.36Z")

# id: gradient top, gradient bottom, badge, glyph. Just the badge on a gradient: scenery
# drawn into the plate was cut off by iOS's corner mask and was noise at icon sizes.
THEMES = {
    "bladeRunner":  ("#123038", "#06090c", "#f0438c", "#ffffff"),
    "dune":         ("#6a3a14", "#130c06", "#e0822f", "#1b1007"),
    "middleEarth":  ("#3a2814", "#120c07", "#d9b060", "#120c07"),
    "synthwave":    ("#1e2a2e", "#090a0c", "#ff7a6e", "#ffffff"),
    "trance":       ("#4a1e0a", "#0c0604", "#ff7a1e", "#1a0a02"),
    "ringWorld":    ("#26381c", "#0b0f0b", "#7fae3a", "#0a1205"),
    "grid":         ("#04303e", "#000407", "#18e4ff", "#00141a"),
}


def icon(theme, top, bottom, badge, glyph, mac):
    if mac:
        x, y, w, rx = 100, 100, 824, 185
        mark = "translate(212 301) scale(3.409)"
    else:
        x, y, w, rx = 0, 0, 1024, 0
        mark = "translate(248 326) scale(3.0)"
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <!-- Generated by tools/theme-icons.py ({theme}). Edit that, not this. -->
  <defs>
    <linearGradient id="plate" x1="0" y1="0" x2="0.35" y2="1">
      <stop offset="0" stop-color="{top}"/><stop offset="1" stop-color="{bottom}"/>
    </linearGradient>
  </defs>
  <rect x="{x}" y="{y}" width="{w}" height="{w}" rx="{rx}" fill="url(#plate)"/>
  <g transform="{mark}">
    <path fill="{badge}" d="{BADGE}"/>
    <circle cx="88" cy="62" r="31" fill="none" stroke="{glyph}" stroke-width="9"/>
    <path d="M88 45v23M88 68l11-11M88 68l-11-11M75 80h26" fill="none" stroke="{glyph}"
          stroke-width="9" stroke-linecap="round" stroke-linejoin="round"/>
  </g>
</svg>
'''


def main():
    os.makedirs(OUT, exist_ok=True)
    for theme, spec in THEMES.items():
        for mac in (True, False):
            name = f"{theme}-{'mac' if mac else 'ios'}.svg"
            with open(os.path.join(OUT, name), "w") as f:
                f.write(icon(theme, *spec, mac))
    print(f"wrote {len(THEMES) * 2} icons to {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
